# The URL the site will be built for
base_url = "https://learn.mimer-ai.eu"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "skill", feed = false, render = false },
    { name = "difficulty", feed = false, render = false },
    { name = "maturity", feed = false, render = false },
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[search]
index_format = "fuse_javascript" # or "fuse_json"

[extra]
# Put all your custom variables here
# Define badge colors for Skill, Difficulty Level, and Maturity
badge_colors = {
    skill = {
        ai = "bg-indigo-700",
        data = "bg-indigo-800",
        programming = "bg-violet-700",
        julia = "bg-purple-700",
        data_science = "bg-cyan-700",
        hpc = "bg-orange-700",
        kubernetes = "bg-blue-700",
        containers = "bg-amber-700",
        cloud = "bg-sky-700",
        life_science = "bg-emerald-700",
        machine_learning = "bg-pink-600",
        mlops = "bg-violet-700",
        agentic = "bg-indigo-700",
        gpu = "bg-red-700",
        distributed_computing = "bg-amber-700",
        pytorch = "bg-orange-700",
        parallel_computing = "bg-lime-700",
        devops = "bg-teal-600"
    },
    difficulty = { beginner = "text-emerald-400", intermediate = "text-amber-400", advanced = "text-red-400" },
    maturity = { alpha = "text-sky-400", beta = "text-blue-400", stable = "text-blue-500" }
}
